openapi: 3.0.4
info:
  title: Text Similarity
  description: Text Similarity is a simple tool for checking the similarity between two texts. It returns the similarity score.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/textsimilarity:
    post:
      summary: Check Similarity
      description: Text Similarity is a simple tool for checking the similarity between two texts. It returns the similarity score.
      operationId: textsimilarity
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  simiarity: 45.83
                  similarityCaseSensitive: 47.22
                  difference:
                    count: 7
                    percentage: 58.33
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text1:
                  type: string
                  description: The first text to compare. Must be less than 1000 characters
                  example: I'm so excited that tomorrow is going to be sunny! Can't wait!
                text2:
                  type: string
                  description: The second text to compare. Must be less than 1000 characters
                  example: We're pretty excited about the weather tomorrow. It's going to be sunny!
              required:
              - text1
              - text2
              example:
                text1: I'm so excited that tomorrow is going to be sunny! Can't wait!
                text2: We're pretty excited about the weather tomorrow. It's going to be sunny!
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
